import assert_moduleDefault from "assert";
import { math as indexjs } from "../../../index";
var assert = {},
    math = indexjs;

describe('pickRandom', function () {
  // Note: pickRandom is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function pickRandom', function () {
    assert.equal(typeof indexjs.pickRandom, 'function');
  })

  it('should LaTeX pickRandom', function () {
    var expression = indexjs.parse('pickRandom([1,2,3])');
    assert.equal(expression.toTex(), '\\mathrm{pickRandom}\\left(\\begin{bmatrix}1\\\\2\\\\3\\\\\\end{bmatrix}\\right)');
  });

});
