import assert_moduleDefault from "assert";
import { math as indexjs } from "../../../index";
var assert = {},
    math = indexjs;

describe('randomInt', function () {
  // Note: randomInt is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function randomInt', function () {
    assert.equal(typeof indexjs.randomInt, 'function');
  })

  it('should LaTeX randomInt', function () {
    var expression = indexjs.parse('randomInt(0,100)');
    assert.equal(expression.toTex(), '\\mathrm{randomInt}\\left(0,100\\right)');
  });
});
