import assert from "assert";
import { indexjs as index_indexjsjs } from "../../../index";

describe('randomInt', function () {
  // Note: randomInt is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function randomInt', function () {
    assert.equal(typeof index_indexjsjs.randomInt, 'function');
  })

  it('should LaTeX randomInt', function () {
    var expression = index_indexjsjs.parse('randomInt(0,100)');
    assert.equal(expression.toTex(), '\\mathrm{randomInt}\\left(0,100\\right)');
  });
});
