import { size as array_sizejs } from "./array";
import { isBoolean as boolean_isBooleanjs } from "./boolean";
import { memoize as function_memoizejs } from "./function";
import { isNumber as number_isNumberjs } from "./number";
import { clone as object_clonejs } from "./object";
import { isString as string_isStringjs } from "./string";
import { type as types_typejs } from "./types";
import { mixin as emitter_mixinjs } from "./emitter";
'use strict';

var array_exportedObj = array_sizejs;
exports['boolean'] = boolean_isBooleanjs;
exports['function'] = function_memoizejs;
var number_exportedObj = number_isNumberjs;
var object_exportedObj = object_clonejs;
var string_exportedObj = string_isStringjs;
var types_exportedObj = types_typejs;
var emitter_exportedObj = emitter_mixinjs;
export { array_exportedObj as array };
export { number_exportedObj as number };
export { object_exportedObj as object };
export { string_exportedObj as string };
export { types_exportedObj as types };
export { emitter_exportedObj as emitter };
